### ISSUE TITLE
JavaFX error met Java SDK 21

### ISSUE THREAD

**Issue by pjmaenh** [HoGentTIN/sql-injection-tester#3]
Oct 07, 2024 3:25:41 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @65af16e'
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:263)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:275)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by MartenBE** [comment]
Can't reproduce, is this still relevant?
